# Generated by Django 3.2.4 on 2021-06-24 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)])),
                ('number', models.IntegerField()),
                ('letter', models.CharField(blank=True, default='', max_length=1)),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'NEED_CLEAN'), ('R', 'NEED_REPAIR')], default='', max_length=3)),
            ],
            options={
                'unique_together': {('farm_number', 'number', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatherRabbit',
            fields=[
                ('rabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.rabbit')),
                ('is_resting', models.BooleanField(default=True)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cage')),
            ],
            bases=('api.rabbit',),
        ),
        migrations.CreateModel(
            name='FatteningCage',
            fields=[
                ('cage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.cage')),
                ('max_capacity', models.PositiveIntegerField(default=1)),
            ],
            bases=('api.cage',),
        ),
        migrations.CreateModel(
            name='MotherCage',
            fields=[
                ('cage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.cage')),
            ],
            bases=('api.cage',),
        ),
        migrations.CreateModel(
            name='MotherRabbit',
            fields=[
                ('rabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.rabbit')),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('P', 'PREGNANT'), ('F', 'FEEDS')], default='', max_length=3)),
                ('last_childbirth', models.DateField(blank=True, null=True)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mothercage')),
            ],
            bases=('api.rabbit',),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fatherrabbit'),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.motherrabbit'),
        ),
        migrations.CreateModel(
            name='FatteningRabbit',
            fields=[
                ('rabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.rabbit')),
                ('is_male', models.BooleanField(blank=True, null=True)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fatteningcage')),
            ],
            bases=('api.rabbit',),
        ),
        migrations.CreateModel(
            name='Bunny',
            fields=[
                ('rabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.rabbit')),
                ('need_jigging', models.BooleanField(default=False)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mothercage')),
            ],
            bases=('api.rabbit',),
        ),
    ]
