# Generated by Django 3.2.4 on 2021-06-24 21:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)])),
                ('number', models.IntegerField()),
                ('letter', models.CharField(default='а', max_length=1)),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'NEED_CLEAN'), ('R', 'NEED_REPAIR')], default='', max_length=3)),
            ],
            options={
                'unique_together': {('farm_number', 'number', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='BaseRabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateTimeField(auto_now_add=True)),
                ('is_ill', models.BooleanField(default=False)),
                ('current_type', models.CharField(choices=[('D', 'DIED'), ('B', 'BUNNY'), ('F', 'FATTENING'), ('P', 'FATHER'), ('M', 'MOTHER')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DeathRabbit',
            fields=[
                ('baserabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baserabbit')),
                ('death_date', models.DateField(auto_now_add=True)),
                ('death_cause', models.CharField(choices=[('S', 'SLAUGHTER'), ('M', 'MOTHER'), ('I', 'ILLNESS'), ('D', 'DISEASE'), ('H', 'HEAT'), ('C', 'COOLING'), ('E', 'EXTRA')], max_length=1)),
            ],
            bases=('api.baserabbit',),
        ),
        migrations.CreateModel(
            name='FatteningCage',
            fields=[
                ('basecage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basecage')),
            ],
            bases=('api.basecage',),
        ),
        migrations.CreateModel(
            name='MotherCage',
            fields=[
                ('basecage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basecage')),
                ('is_parallel', models.BooleanField(default=False)),
            ],
            bases=('api.basecage',),
        ),
        migrations.CreateModel(
            name='MotherRabbit',
            fields=[
                ('baserabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baserabbit')),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('P', 'PREGNANT'), ('F', 'FEEDS')], default='', max_length=3)),
                ('last_childbirth', models.DateField(blank=True, null=True)),
                ('cage', models.ForeignKey(limit_choices_to={'status': []}, on_delete=django.db.models.deletion.PROTECT, to='api.mothercage')),
            ],
            bases=('api.baserabbit',),
        ),
        migrations.CreateModel(
            name='FatteningRabbit',
            fields=[
                ('baserabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baserabbit')),
                ('is_male', models.BooleanField(blank=True, null=True)),
                ('cage', models.ForeignKey(limit_choices_to={'status': []}, on_delete=django.db.models.deletion.PROTECT, to='api.fatteningcage')),
            ],
            bases=('api.baserabbit',),
        ),
        migrations.CreateModel(
            name='FatherRabbit',
            fields=[
                ('baserabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baserabbit')),
                ('is_resting', models.BooleanField(default=True)),
                ('cage', models.ForeignKey(limit_choices_to={'status': []}, on_delete=django.db.models.deletion.PROTECT, to='api.basecage')),
            ],
            bases=('api.baserabbit',),
        ),
        migrations.CreateModel(
            name='Bunny',
            fields=[
                ('baserabbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baserabbit')),
                ('need_jigging', models.BooleanField(default=False)),
                ('cage', models.ForeignKey(limit_choices_to={'status': []}, on_delete=django.db.models.deletion.PROTECT, to='api.mothercage')),
            ],
            bases=('api.baserabbit',),
        ),
        migrations.AddField(
            model_name='baserabbit',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fatherrabbit'),
        ),
        migrations.AddField(
            model_name='baserabbit',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.motherrabbit'),
        ),
    ]
