# Generated by Django 3.2.4 on 2021-06-25 09:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='letter',
            field=models.CharField(choices=[('а', 'LETTER_A'), ('б', 'LETTER_B'), ('в', 'LETTER_V'), ('г', 'LETTER_G')], default='а', max_length=1),
        ),
        migrations.AlterField(
            model_name='deathrabbit',
            name='death_cause',
            field=models.CharField(choices=[('S', 'CAUSE_SLAUGHTER'), ('M', 'CAUSE_MOTHER'), ('I', 'CAUSE_ILLNESS'), ('D', 'CAUSE_DISEASE'), ('H', 'CAUSE_HEAT'), ('C', 'CAUSE_COOLING'), ('E', 'CAUSE_EXTRA')], max_length=1),
        ),
        migrations.AlterField(
            model_name='motherrabbit',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('P', 'STATUS_PREGNANT'), ('F', 'STATUS_FEEDS')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='current_type',
            field=models.CharField(choices=[('D', 'TYPE_DIED'), ('B', 'TYPE_BUNNY'), ('F', 'TYPE_FATTENING'), ('P', 'TYPE_FATHER'), ('M', 'TYPE_MOTHER')], default='B', max_length=1),
        ),
    ]
