# Generated by Django 3.2.4 on 2021-07-05 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210704_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbit',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='rabbit',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='beforeslaughterinspection',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pregnancyinspection',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
