# Generated by Django 3.2.4 on 2021-06-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210625_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeathRabbit',
            new_name='DeadRabbit',
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='current_type',
            field=models.CharField(choices=[('D', 'TYPE_DEAD'), ('B', 'TYPE_BUNNY'), ('F', 'TYPE_FATTENING'), ('P', 'TYPE_FATHER'), ('M', 'TYPE_MOTHER')], default='B', max_length=1),
        ),
    ]
