# Generated by Django 3.2.4 on 2021-06-25 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rabbit_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
