# Generated by Django 3.2.4 on 2021-07-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210706_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunnyhistory',
            name='cage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mothercage'),
        ),
        migrations.AlterField(
            model_name='fatherrabbithistory',
            name='cage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.fatteningcage'),
        ),
        migrations.AlterField(
            model_name='fatteningrabbithistory',
            name='cage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.fatteningcage'),
        ),
        migrations.AlterField(
            model_name='motherrabbithistory',
            name='cage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mothercage'),
        ),
    ]
