# Generated by Django 3.2.4 on 2021-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rabbit_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='breed',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
