# Generated by Django 3.2.4 on 2021-06-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rabbit_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RabbitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vaccinated', models.BooleanField(blank=True, null=True)),
                ('is_ill', models.BooleanField(blank=True, null=True)),
                ('current_type', models.CharField(max_length=1)),
                ('rabbit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.rabbit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
