# Generated by Django 3.2.4 on 2021-06-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rabbit_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='breed',
            field=models.TextField(default=''),
        ),
    ]
