# Generated by Django 3.2.4 on 2021-06-29 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210629_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbithistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rabbithistory',
            unique_together={('rabbit', 'time')},
        ),
    ]
