# Generated by Django 3.2.4 on 2021-07-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210711_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadRabbitHistory',
            fields=[
                ('rabbithistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.rabbithistory')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fatteningrabbit')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
            bases=('api.rabbithistory',),
        ),
    ]
