# Generated by Django 3.2.4 on 2021-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210629_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='breed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
