# Generated by Django 3.2.4 on 2021-06-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rabbit_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='breed',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
