# Generated by Django 3.2.4 on 2021-06-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rabbithistory_rabbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbithistory',
            name='current_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rabbithistory',
            name='is_ill',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rabbithistory',
            name='is_vaccinated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='FatteningRabbitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cage', models.IntegerField(blank=True, default=None, null=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fatteningrabbit')),
            ],
            options={
                'unique_together': {('rabbit', 'time')},
            },
        ),
    ]
