# Generated by Django 3.2.4 on 2021-07-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deadrabbithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadrabbithistory',
            name='rabbit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deadrabbit'),
        ),
    ]
