# Generated by Django 3.2.4 on 2021-06-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210630_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherRabbitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('last_childbirth', models.DateField(blank=True, default=None, null=True)),
                ('cage', models.IntegerField(blank=True, default=None, null=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motherrabbit')),
            ],
            options={
                'unique_together': {('rabbit', 'time')},
            },
        ),
        migrations.CreateModel(
            name='FatherRabbitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_resting', models.BooleanField(blank=True, default=None, null=True)),
                ('cage', models.IntegerField(blank=True, default=None, null=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fatherrabbit')),
            ],
            options={
                'unique_together': {('rabbit', 'time')},
            },
        ),
        migrations.CreateModel(
            name='BunnyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('need_jigging', models.BooleanField(blank=True, default=None, null=True)),
                ('cage', models.IntegerField(blank=True, default=None, null=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bunny')),
            ],
            options={
                'unique_together': {('rabbit', 'time')},
            },
        ),
    ]
