# Generated by Django 3.2.4 on 2021-06-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_rabbit_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbit',
            name='breed',
        ),
    ]
