# Generated by Django 3.2.4 on 2021-07-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bunnyhistory_fatherrabbithistory_motherrabbithistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunny',
            name='need_jigging',
        ),
        migrations.RemoveField(
            model_name='bunnyhistory',
            name='need_jigging',
        ),
        migrations.RemoveField(
            model_name='fatherrabbit',
            name='is_resting',
        ),
        migrations.RemoveField(
            model_name='fatherrabbithistory',
            name='is_resting',
        ),
        migrations.RemoveField(
            model_name='motherrabbit',
            name='last_childbirth',
        ),
        migrations.RemoveField(
            model_name='motherrabbit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='motherrabbithistory',
            name='last_childbirth',
        ),
        migrations.AddField(
            model_name='motherrabbit',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fatherrabbit',
            name='cage',
            field=models.ForeignKey(limit_choices_to={'status': []}, on_delete=django.db.models.deletion.PROTECT, to='api.fatteningcage'),
        ),
        migrations.AlterField(
            model_name='motherrabbit',
            name='cage',
            field=models.ForeignKey(limit_choices_to={'status': []}, on_delete=django.db.models.deletion.PROTECT, to='api.cage'),
        ),
    ]
