# Generated by Django 3.2.4 on 2021-07-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.breed'),
            preserve_default=False,
        ),
    ]
