# Generated by Django 3.2.4 on 2021-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rabbit_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterplan',
            name='plan_ptr',
        ),
        migrations.AddField(
            model_name='plan',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('S', 'SLAUGHTER'), ('M', 'MATING')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MatingPlan',
        ),
        migrations.DeleteModel(
            name='SlaughterPlan',
        ),
    ]
