# Generated by Django 3.2.4 on 2021-07-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210714_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='type',
        ),
        migrations.AddField(
            model_name='fatteningrabbit',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan'),
        ),
    ]
