# Generated by Django 3.2.4 on 2021-07-02 19:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherrabbithistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='is_ill',
        ),
        migrations.RemoveField(
            model_name='rabbithistory',
            name='is_ill',
        ),
        migrations.AddField(
            model_name='motherrabbithistory',
            name='is_pregnant',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='warning_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NE', 'NOT_EAT'), ('ND', 'NOT_DRINK'), ('GS', 'GOT_SICK')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='rabbithistory',
            name='warning_status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
