# Generated by Django 3.2.4 on 2021-07-03 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210702_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatingPlan',
            fields=[
                ('plan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.plan')),
                ('number_pairs', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('api.plan',),
        ),
        migrations.CreateModel(
            name='SlaughterPlan',
            fields=[
                ('plan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.plan')),
                ('number_rabbits', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('api.plan',),
        ),
        migrations.CreateModel(
            name='SlaughterTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.task')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fatteningrabbit')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.task',),
        ),
        migrations.CreateModel(
            name='MatingTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.task')),
                ('father_rabbit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fatherrabbit')),
                ('mother_rabbit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.motherrabbit')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.task',),
        ),
    ]
