# Generated by Django 3.2.4 on 2021-07-03 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210702_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('bags_number', models.IntegerField()),
            ],
        ),
    ]
