# Generated by Django 3.2.4 on 2021-07-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_typegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mothercage',
            old_name='is_parallel',
            new_name='has_right_womb',
        ),
    ]
