# Generated by Django 3.2.4 on 2021-07-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_is_parallel_mothercage_has_right_womb'),
        ('api', '0017_auto_20210724_1424'),
    ]

    operations = [
    ]
