# Generated by Django 3.2.4 on 2021-07-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20210725_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunnyjiggingtask',
            name='females',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunnyjiggingtask',
            name='males',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slaughterinspectiontask',
            name='weights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
