# Generated by Django 3.2.4 on 2021-07-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_feedbatch'),
        ('api', '0018_merge_20210725_1600'),
    ]

    operations = [
    ]
