# Generated by Django 3.2.4 on 2021-07-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210726_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunnyjiggingtask',
            name='females',
        ),
    ]
