# Generated by Django 3.2.4 on 2021-07-27 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_0015_feedbatch_0018_merge_20210725_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbatch',
            name='bags_left',
        ),
        migrations.RemoveField(
            model_name='feedbatch',
            name='total_bags_number',
        ),
        migrations.AddField(
            model_name='feedbatch',
            name='common_bags_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbatch',
            name='mother_bags_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbatch',
            name='total_common_bags_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbatch',
            name='total_mother_bags_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbatch',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 27, 0, 50, 32, 226163)),
        ),
    ]
