# Generated by Django 3.2.4 on 2021-07-27 00:58
import datetime

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210727_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbatch',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
