# Generated by Django 3.2.4 on 2021-07-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_bunnyjiggingtask_females'),
        ('api', '0021_alter_feedbatch_delivery_date'),
    ]

    operations = [
    ]
