# Generated by Django 3.2.4 on 2021-07-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20210727_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBatch',
        ),
    ]
