# Generated by Django 3.2.4 on 2021-07-27 21:16
import datetime

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_feedbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('stocks_change', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NursingMotherFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('stocks_change', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
