# Generated by Django 3.2.4 on 2021-07-29 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_commonfeeds_nursingmotherfeeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToFatteningTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.task')),
                ('cage_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fatteningcage')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rabbit')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
            bases=('api.task',),
        ),
        migrations.AlterModelManagers(
            name='bunny',
            managers=[
                ('all_current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deadrabbit',
            managers=[
                ('all_current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fatherrabbit',
            managers=[
                ('all_current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fatteningrabbit',
            managers=[
                ('all_current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='motherrabbit',
            managers=[
                ('all_current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='slaughterinspectiontask',
            name='weights',
        ),
        migrations.AlterField(
            model_name='slaughtertask',
            name='rabbit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fatteningrabbit'),
        ),
        migrations.DeleteModel(
            name='FatteningSlaughterTask',
        ),
    ]
