# Generated by Django 3.2.4 on 2021-07-29 18:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210729_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterinspectiontask',
            name='weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
