# Generated by Django 3.2.4 on 2022-01-04 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_slaughterinspectiontask_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterinspectiontask',
            name='weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
