# Generated by Django 3.2.4 on 2021-08-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_slaughterinspectiontask_weights'),
        ('api', '0027_rabbithistory_weight'),
    ]

    operations = [
    ]
