# Generated by Django 3.2.4 on 2021-08-01 23:07

import api.models._feeds
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_delete_beforeslaughterinspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('stocks', models.SmallIntegerField(validators=[api.models._feeds._stocks_validator])),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CommonFeeds',
        ),
        migrations.DeleteModel(
            name='NursingMotherFeeds',
        ),
        migrations.CreateModel(
            name='FatteningFeeds',
            fields=[
                ('feeds_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.feeds')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
            bases=('api.feeds',),
        ),
        migrations.CreateModel(
            name='MotherFeeds',
            fields=[
                ('feeds_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.feeds')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
            bases=('api.feeds',),
        ),
    ]
