# Generated by Django 3.2.4 on 2021-08-08 17:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_auto_20210801_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMotherRabbit',
            fields=[
                ('rabbit_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='api.rabbit')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('birthday', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('is_male', models.BooleanField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('current_type', models.CharField(choices=[('D', 'TYPE_DEAD'), ('B', 'TYPE_BUNNY'), ('F', 'TYPE_FATTENING'), ('P', 'TYPE_FATHER'), ('M', 'TYPE_MOTHER')], default='B', max_length=1)),
                ('warning_status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NE', 'NOT_EAT'), ('ND', 'NOT_DRINK'), ('GS', 'GOT_SICK')], default='', max_length=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('breed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.breed')),
                ('cage', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'status': []}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.mothercage')),
                ('father', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fatherrabbit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.motherrabbit')),
            ],
            options={
                'verbose_name': 'historical mother rabbit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFatteningRabbit',
            fields=[
                ('rabbit_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='api.rabbit')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('birthday', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('is_male', models.BooleanField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('current_type', models.CharField(choices=[('D', 'TYPE_DEAD'), ('B', 'TYPE_BUNNY'), ('F', 'TYPE_FATTENING'), ('P', 'TYPE_FATHER'), ('M', 'TYPE_MOTHER')], default='B', max_length=1)),
                ('warning_status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NE', 'NOT_EAT'), ('ND', 'NOT_DRINK'), ('GS', 'GOT_SICK')], default='', max_length=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('breed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.breed')),
                ('cage', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'status': []}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fatteningcage')),
                ('father', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fatherrabbit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.motherrabbit')),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.plan')),
            ],
            options={
                'verbose_name': 'historical fattening rabbit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFatherRabbit',
            fields=[
                ('rabbit_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='api.rabbit')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('birthday', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('is_male', models.BooleanField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('current_type', models.CharField(choices=[('D', 'TYPE_DEAD'), ('B', 'TYPE_BUNNY'), ('F', 'TYPE_FATTENING'), ('P', 'TYPE_FATHER'), ('M', 'TYPE_MOTHER')], default='B', max_length=1)),
                ('warning_status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NE', 'NOT_EAT'), ('ND', 'NOT_DRINK'), ('GS', 'GOT_SICK')], default='', max_length=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('breed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.breed')),
                ('cage', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'status': []}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fatteningcage')),
                ('father', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fatherrabbit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.motherrabbit')),
            ],
            options={
                'verbose_name': 'historical father rabbit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBunny',
            fields=[
                ('rabbit_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='api.rabbit')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('birthday', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('is_male', models.BooleanField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('current_type', models.CharField(choices=[('D', 'TYPE_DEAD'), ('B', 'TYPE_BUNNY'), ('F', 'TYPE_FATTENING'), ('P', 'TYPE_FATHER'), ('M', 'TYPE_MOTHER')], default='B', max_length=1)),
                ('warning_status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NE', 'NOT_EAT'), ('ND', 'NOT_DRINK'), ('GS', 'GOT_SICK')], default='', max_length=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('breed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.breed')),
                ('cage', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'status': []}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.mothercage')),
                ('father', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fatherrabbit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.motherrabbit')),
            ],
            options={
                'verbose_name': 'historical bunny',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
