# Generated by Django 3.2.4 on 2021-08-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_historicalbunny_historicalfatherrabbit_historicalfatteningrabbit_historicalmotherrabbit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadrabbithistory',
            name='rabbit',
        ),
        migrations.RemoveField(
            model_name='deadrabbithistory',
            name='rabbithistory_ptr',
        ),
        migrations.RemoveField(
            model_name='fatherrabbithistory',
            name='cage',
        ),
        migrations.RemoveField(
            model_name='fatherrabbithistory',
            name='rabbit',
        ),
        migrations.RemoveField(
            model_name='fatherrabbithistory',
            name='rabbithistory_ptr',
        ),
        migrations.RemoveField(
            model_name='fatteningrabbithistory',
            name='cage',
        ),
        migrations.RemoveField(
            model_name='fatteningrabbithistory',
            name='rabbit',
        ),
        migrations.RemoveField(
            model_name='fatteningrabbithistory',
            name='rabbithistory_ptr',
        ),
        migrations.RemoveField(
            model_name='motherrabbithistory',
            name='cage',
        ),
        migrations.RemoveField(
            model_name='motherrabbithistory',
            name='rabbit',
        ),
        migrations.RemoveField(
            model_name='motherrabbithistory',
            name='rabbithistory_ptr',
        ),
        migrations.DeleteModel(
            name='BunnyHistory',
        ),
        migrations.DeleteModel(
            name='DeadRabbitHistory',
        ),
        migrations.DeleteModel(
            name='FatherRabbitHistory',
        ),
        migrations.DeleteModel(
            name='FatteningRabbitHistory',
        ),
        migrations.DeleteModel(
            name='MotherRabbitHistory',
        ),
        migrations.DeleteModel(
            name='RabbitHistory',
        ),
    ]
