# Generated by Django 3.2.4 on 2021-08-10 00:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_historicalbunnyjiggingtask_historicalmatingtask_historicalslaughterinspectiontask_historicalslaughte'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bunny',
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deadrabbit',
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fatherrabbit',
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fatteningrabbit',
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='motherrabbit',
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rabbit',
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalbunny',
            name='current_type',
        ),
        migrations.RemoveField(
            model_name='historicalfatherrabbit',
            name='current_type',
        ),
        migrations.RemoveField(
            model_name='historicalfatteningrabbit',
            name='current_type',
        ),
        migrations.RemoveField(
            model_name='historicalmotherrabbit',
            name='current_type',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='current_type',
        ),
    ]
