# Generated by Django 3.2.4 on 2021-08-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_mothercage_womb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mothercage',
            name='has_right_womb',
        ),
        migrations.AlterField(
            model_name='mothercage',
            name='womb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_womb', to='api.mothercage'),
        ),
    ]
